### PR TITLE
Break up into more modules

### PR DESCRIPTION
**Pull request by treeowl**
* Separate internals from the public API and from each other.

* Add pattern synonyms for understanding `SeqT` as its view.

### CODE REVIEW

**Comment by treeowl** [comment]
This PR could really use a proof that `toView . fromView = id` and `fromView . toView = id`. I'll try to do that by tomorrow.

**Comment by treeowl** [comment]
I have a proof that `toView . fromView = id`. Going the other way is a bit trickier, because we want to consider certain queues equivalent.

**Comment by dagit** [comment]
Oh geez. I just now saw this. For some reason github didn't show me there were others PRs. Sorry.

**Comment by dagit** [comment]
Um, well, the web editor let me merge it by just deleting my changes. I've used that feature of github before and I didn't really mean to commit it to the PR, but that's where we are now. I can add the INLINE's back no problem.

**Comment by dagit** [comment]
The proof of the other direction would be cool, but I want to get this merged so I don't clobber you again :) So if you work on out, please send it.

**Comment by treeowl** [comment]
All right! Thanks!

**Pull request merged**
