### PR TITLE
Make AsUnitLoop more compact

### PR DESCRIPTION
**Pull request by treeowl**
* We can save memory and indirection by being a bit tricky with
our representation of `AsUnitLoop`. Do that.

* Move `AsUnitLoop` to its own module to wall off the mess.

* Add a few basic class instances for `AsUnitLoop`: `Show`, `Read`,
  `Eq`, `Ord`, `Semigroup`, and `Monoid`.

* Add a `getUL` convenience function for deconstructing
  `AsUnitLoop`.

### CODE REVIEW

**Comment by treeowl** [comment]
I haven't checked exactly which GHC version to use as the cutoff for where pattern synonyms are sufficiently well-behaved to want to do this. I *think* it's 8.4, but I can't swear to it.

**Comment by treeowl** [comment]
In case you're wondering: yes, the compiler *should* know how to do this all by itself. Sadly, it doesn't.

**Comment by dagit** [comment]
Thanks!

This all looks good, but I admit I haven't really developed an intuition for the internal type aligned sequence stuff so take that with a grain of salt. Anyway, I would like to merge this code. However, two things:

* a) I am wondering can we quantify how much savings we get from this representation change? I'm imagining some sort of microbenchmarks we can run that measure memory and runtime performance of some trivial examples. Maybe adding a test section to the cabal file full of microbechmarks?  Perhaps turning some of these benchmarks into something we can run? https://github.com/atzeus/reflectionwithoutremorse

* b) Can you please follow up with respect to the pattern synonym thing to figure out your minimum version? I was implicitly hoping to support the same GHC version range as `LogicT` (I believe something like `base >= 4.3`), although I'm not currently setup with an easy way to test old versions of GHC.

Does that sound reasonable?

**Comment by treeowl** [comment]
In the original version, if you have an `AsUnitLoop x () ()`, what you really have is a pointer to an `AsUnitLoop` heap object consisting of a one-word header followed by a pointer to an `x`. In the new version, you just have a pointer to an `x`. So that's two fewer words in memory, and one less pointer to follow, per link in the chain.

The best and easiest way to pin down the version confidently is to set up testing for GitHub and throw it at a bunch of versions.

**Comment by dagit** [comment]
Just in case it wasn't clear, would you be willing to tackle (a) and (b) as part of this pull request?

> The best and easiest way to pin down the version confidently is to set up testing for GitHub and throw it at a bunch of versions.

That sounds quite reasonable. I assume if we went that route, who ever configures it would need some related permissions on the repo? I've always used things like travis ci with github in the past but it seems that these github actions are usually easier. I just don't have any experience with them yet.

**Comment by dagit** [comment]
Actually, setting up github actions seems very easy. I found a config recommended for Haskell and it seems to be working. I'll have to throw in some older GHC's once we see it working on the current configuration. Looks like base 4.3 corresponds to GHC 7.0.1: https://wiki.haskell.org/Base_package

**Comment by treeowl** [comment]
Honestly, setting that CI stuff up is really not my strong suit.

**Comment by dagit** [comment]
When you get a chance, can you resynchronize this branch with `main` . I believe that will force it to run against the CI. Looks like the oldest version of ghc that is supposed by type-aligned is `7.4.2` due to `DataKinds`. So that's my new target, if possible.

**Comment by treeowl** [comment]
Do you really need to go that far back? Not many packages do, let alone new
ones, and very few people are using such old GHC versions.

**Comment by dagit** [comment]
Well, it looks like even though 7.4.2 is very old your code compiles just fine in that version. So I'm going to merge this and leave that as the lower bound for now. We can revisit it if it becomes an issue but it's kind of nice knowing it works on a wide range of older GHCs.

Thanks again for the contributions!

**Comment by dagit** [comment]
BTW, before your changes:

```
IO with msplit:                                                          
Batch generated in: 1.4062999999999999 seconds                                                                                                     
Batch generated in: 1.358109 seconds                                     
Batch generated in: 1.389281 seconds                                                                                                               
Batch generated in: 1.3897979999999999 seconds                                                                                                     
Batch generated in: 1.365232 seconds                                                                                                               
Total time: 6.908881 seconds
After your changes:
```

```
IO with msplit:
Batch generated in: 1.2426519999999999 seconds
Batch generated in: 1.195139 seconds
Batch generated in: 1.251883 seconds
Batch generated in: 1.196281 seconds
Batch generated in: 1.230983 seconds
Total time: 6.117094 seconds
```

**Comment by treeowl** [comment]
Nice! Glad to see it made a measurable difference, if not a large one.

**Comment by dagit** [comment]
We’re about 10x slower than normal LogicT, so every little bit helps :)

**Pull request merged**
