### PR TITLE
Inline based optimizations

### PR DESCRIPTION
**Pull request by dagit**
I also switched observeAllT to use a worker/wrapper
pattern.

I just sort of went nuts marking things as `INLINE` but one of the biggest payoffs was actually `>>=`.

```
SeqT IO with msplit:
Batch generated in: 0.546473 seconds
Batch generated in: 0.521952 seconds
Batch generated in: 0.506858 seconds
Batch generated in: 0.536403 seconds
Batch generated in: 0.524648 seconds
Total time: 2.636488 seconds

SeqT Identity with msplit:
Batch generated in: 0.60177 seconds
Batch generated in: 0.5683549999999999 seconds
Batch generated in: 0.6440279999999999 seconds
Batch generated in: 0.66166 seconds
Batch generated in: 0.5953309999999999 seconds
Total time: 3.071288 seconds

SeqT Identity without msplit:
Batch generated in: 0.6014269999999999 seconds
Batch generated in: 0.641728 seconds
Batch generated in: 0.623448 seconds
Batch generated in: 0.550899 seconds
Batch generated in: 0.635666 seconds
Total time: 3.053315 seconds

LogicT Identity without msplit:
Batch generated in: 0.115443 seconds
Batch generated in: 0.141348 seconds
Batch generated in: 0.130463 seconds
Batch generated in: 0.117857 seconds
Batch generated in: 0.163205 seconds
Total time: 0.668446 seconds
```

### CODE REVIEW

**Comment by dagit** [comment]
@treeowl You might find this interesting.

**Comment by treeowl** [comment]
This is going to make my PR pretty hard to rebase.

**Comment by treeowl** [comment]
I don't understand what your benchmark numbers are referring to.

**Comment by dagit** [comment]
> This is going to make my PR pretty hard to rebase.

Sorry, although I think it should be easy to merge because aside from rewriting `observeAllT` all the other changes are just adding `INLINE` or `INLINEABLE` pragma. You could just prefer your version in a merge and then add them back. Something like this: https://stackoverflow.com/questions/17704119/how-to-prefer-files-from-one-branch-during-a-merge

> I don't understand what your benchmark numbers are referring to.

Yeah, I need to publish the benchmark. It's just a simple iterative deepening depth first search that generates paths and then I convert those `streamly` streams in batches of half a million. Then output them all. The streamly stuff isn't really necessary, it was just part of a real workload I had. Anyway, when I uploaded 0.1.0.0 there was a factor 10x between the last output (`LogicT`) and any of the `SeqT` outputs. Now the gap is about 4.3x.

**Comment by dagit** [comment]
I should add, the other implication here is that anything you can do in your rewrite to optimize `>>=` will have a pretty solid pay off.

**Comment by treeowl** [comment]
My big PR just reorganizes the modules (a bunch) and adds pattern synonyms. I'll just have to figure out the rebase.

**Pull request merged**
